---
title: "Code"
author: "Matthew Hudes"
date: "1/20/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
devtools::load_all(".")
# devtools::install_github("emma-morgan/QualtricsTools")
# library(tidyverse)
# library(QualtricsTools)

# qsf_path = here::here("Testing stuff", "Example data", "QualtricsTools_Sample_Survey_Winter2021.qsf")
# csv_path = here::here("Testing stuff", "Example data", "QualtricsTools+Sample+Survey+Winter2021_January+23,+2021_14.59_DataTable.csv")

qsf_path = here::here("Testing stuff", "Example data", "Long_Exhaustive_Sample_Survey.qsf")
csv_path = here::here("Testing stuff", "Example data", "Long_Exhaustive_Sample_Survey_January+29,+2021_10.20_DataTable.csv")

# qsf_path = here::here("Testing stuff", "Example data", "Grad_Admin.qsf")
# csv_path = here::here("Testing stuff", "Example data", "Grad_Admin.csv")

headerrows = 3

get_setup(
  qsf_path = qsf_path,
  csv_path = csv_path,
  headerrows = headerrows
)
```


## Lets make a results table with the survey

```{r}

make_results_tables(
  output_dir =  here::here("Testing stuff"),
  filename = "Long Results Tables Data Table.docx"
)


```



## Lets make a text appendix with the survey

```{r}

make_text_appendices(
  output_dir =  here::here("Testing stuff"),
  filename = "Long Text Appendix Data Table.docx"
)


```





## Lets open the app

```{r}

app()

```


# Coded Comments

```{r}
# devtools::load_all(".")

qsf_path = here::here("Testing stuff", "Comment Coding Test", "CSV, QSF", "GSASSOE_Graduate_Admissions_Survey_2020 (2).qsf")
csv_path = here::here("Testing stuff", "Comment Coding Test", "CSV, QSF", "ResponseIDCol1_GSAS_SOE+Graduate+Admissions+Survey+2020_February+8,+2021.csv")

# Load and process the survey
get_setup(qsf_path = qsf_path,
          csv_path = csv_path,
          headerrows = 3)

```


```{r}
make_coded_comments(
    sheets_dir = here::here("Testing stuff", "Comment Coding Test", "Comment Coding Sheets"),
    output_dir = here::here("Testing stuff", "Comment Coding Test"),
    filename = "Testing Comment Coding.docx",
    n_threshold = 15)
```












```{r}



# Load the package as it is and load tidyverse
devtools::load_all(".")

# Get stuff in from the files from the survey
get_setup(
  qsf_path = here::here("Testing stuff", "sample", "Better_Sample_Survey.qsf"),
  csv_path = here::here("Testing stuff", "sample", "Better_Sample_Survey_March+17,+2021_04.02.csv"),
  headerrows = 3
)

# Save its stuff as an RDS file
sample_original_first_rows <- original_first_rows
saveRDS(sample_original_first_rows, file = here::here("data", "sample_original_first_rows.rds"))

sample_responses <- responses
saveRDS(sample_responses, file = here::here("data", "sample_responses.rds"))


sample_survey <- survey
saveRDS(sample_survey, file = here::here("data", "sample_survey.rds"))

```










