---
title: "Scratch_Work"
author: "Matthew Hudes"
date: "4/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 


# Set up stuff

```{r}
devtools::load_all(".")
app()

# devtools::install_github("Matthewh19/QualtricsTools", ref = "More_Shiny_Work")
library(QualtricsTools)
```



# Found this package called shinyFiles

```{r}
devtools::install_github("thomasp85/shinyFiles", force = TRUE)

#devtools::install_github("Matthewh19/shinyFiles", ref = "Pencil_Paste_Work", force = TRUE)

library(shinyFiles)
```




# Reviewing comment coding

```{r}

get_setup(qsf_path = here::here("data", "Sample Surveys", "Better Sample Survey", "Better_Sample_Survey.qsf"),
          csv_path = here::here("data", "Sample Surveys", "Better Sample Survey", "Better_Sample_Survey.csv"),
          headerrows = 3)

## Old formatt:
make_coded_comments(
    sheets_dir = here::here("data", "Sample Surveys", "Comment Coding", "Coded Comments"),
    output_dir = here::here("Scratch_Work", "Example Coded Comments"),
    filename = "Testing Comment Coding.docx",
    n_threshold = 2,
    code_type = "fmp")


## Using Nvivo
make_coded_comments(
    sheets_dir = here::here("data", "Sample Surveys", "Better Sample Survey", "Comment Coding NVivo"),
    output_dir = here::here("Scratch_Work", "Example Coded Comments"),
    filename = "Testing Nvivo Comment Coding.docx",
    n_threshold = 2)


## Split
make_split_coded_comments(
    sheets_dir = here::here("data", "Sample Surveys", "Comment Coding", "Coded Comments"),
    output_dir = here::here("Scratch_Work", "Example Coded Comments"),
    n_threshold = 2,
    split_by = c("q5_position")
)


```




## Seeing how qtSkip and stuff works
```{r}

get_setup(qsf_path = here::here("data", "Sample Surveys", "Better Sample Survey", "Better_Sample_Survey.qsf"),
          csv_path = here::here("data", "Sample Surveys", "Better Sample Survey", "Better_Sample_Survey.csv"),
          headerrows = 3)

questions[[find_question_index(questions, "q1_recent")]][['qtSkip']] <- TRUE

blocks <- questions_into_blocks(questions, blocks)


make_results_tables(output_dir= here::here("Scratch_Work"))
make_text_appendices(output_dir=here::here("Scratch_Work"))

```






## Lets review the reshaping for Tableau stuff

```{r}
get_setup(qsf_path = here::here("data", "Sample Surveys", "Better Sample Survey", "Better_Sample_Survey.qsf"),
          csv_path = here::here("data", "Sample Surveys", "Better Sample Survey", "Better_Sample_Survey.csv"),
          headerrows = 3)

lean_responses <- lean_responses(blocks, responses)
qdict <- create_response_column_dictionary(blocks, original_first_rows[1,], flow_from_survey(survey))
panel_df <- create_panel_data(c("q2_favorite", "q4_rank_2"), responses, lean_dict, qdict)

# Here we use fwrite over write.csv because fwrite takes advantage of a 
# computer having multiple cores. The vast majority of modern computers do have
# multiple cores, and so fwrite often performs significantly better than write.csv.
# fwrite is from the data.table package which may need to be installed.

if(!require('data.table')) { install.packages('data.table') } # Ensure data.table is installed.
library('data.table') # Load data.table package for the fwrite function.
fwrite(x = lean_responses, file = "C:/Users/username/Desktop/lean_dictionary.csv", row.names=FALSE)
fwrite(x = qdict, file = "C:/Users/username/Desktop/question_dictionary.csv", row.names=FALSE)
fwrite(x = panel_df, file = "C:/Users/username/Desktop/panel_data.csv", row.names=FALSE)

# While we can use WriteXLS, fwrite and write.csv are more reliable options because 
# Excel files can only support up to a finite number of rows where as CSVs are much less
# limited in length. Here is an example of how to write an Excel file with three sheets containing 
# each of these documents.
if(!require('WriteXLS')) { install.packages('WriteXLS') } # Ensure WriteXLS is installed.    
library(WriteXLS)    
WriteXLS(c("lean_dict", "qdict", "panel_df"), ExcelFileName = "C:/Users/username/Desktop/example_long_and_lean.xls")


```







